[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA redirects handled by _redirects file

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"
